version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev.x"
    groups:
      java-dependencies:
        patterns:
          - "*"
